### ISSUE TITLE
How to handle JEFException ?

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#42]
Hi,
There is a case where I need to restart crawler, in which I am calling **fileSystemCollector.stop();** and then calling **fileSystemCollector.start(false);** However when start is getting called below exception is getting thrown and since its handled in norconex's JobSuite class, I am not even able to catch it.

FATAL [JobSuite] Job suite execution failed: rty
com.norconex.jef4.JEFException: JOB SUITE STOPPING. There is an instance of this job suite currently stopping.  Wait for it to stop, or terminate the process.
        at com.norconex.jef4.suite.JobSuite.ensureValidExecutionState(JobSuite.java:520)
        at com.norconex.jef4.suite.JobSuite.initialize(JobSuite.java:465)
        at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:277)
        at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168)
        at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:132)

Its just that if we get state of the ongoing crawler, it would be great.

**Comment by jayjamba** [comment]
I am launching FILE collector and not HTTP collector. The problem is sequence of my code is something like 
**fileSystemCollector.stop();
fileSystemCollector.start(false);** 

However when start is getting called below exception is getting thrown and since its handled in norconex's JobSuite class, I am not even able to catch it.

FATAL [JobSuite] Job suite execution failed: rty
com.norconex.jef4.JEFException: JOB SUITE STOPPING. There is an instance of this job suite currently stopping. Wait for it to stop, or terminate the process.
at com.norconex.jef4.suite.JobSuite.ensureValidExecutionState(JobSuite.java:520)
at com.norconex.jef4.suite.JobSuite.initialize(JobSuite.java:465)
at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:277)
at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168)
at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:132)


`yourCollectorInstance.getJobSuite().getRootStatus().getState();`

This gives me null pointer exception coz in norconex's file crawler's start method job suite is nullified in finally block.

**Comment by essiembre** [comment]
This exception is normal when trying to start an already running collector. 

The latest [collector-core snapshot](https://www.norconex.com/collectors/collector-core/download) has a new AbstractCollector#getState() method that will give you the state safely.  Use that method instead.  When the collector is not running, you will get an UNKNOWN state.

If you want to obtain the state in a safer way (independent), you can call this method instead:
```java
com.norconex.jef4.status.JobSuiteStatusSnapshot.newSnapshot(File suiteIndex);
```
Please give either a try and confirm.
