### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-filesystem#5]
I lowered threads to 1 and this seems to work. Not sure if that was the fix or that a corrupted file was the culprit.

[EDIT] Ran into issue again, tmp dir contained a lot of tika files. Increasing file limit solved issue. Maybe note that somewhere in documentation.

Test Filesystem: 2016-05-01 13:48:43 ERROR - Test Filesystem: Could not process document: [url] (Cannot queue document addition.  Ref:[url])
com.norconex.committer.core.CommitterException: Cannot queue document addition.  Ref: [url]
	at com.norconex.committer.core.impl.FileSystemCommitter.add(FileSystemCommitter.java:113)
	at com.norconex.committer.core.AbstractFileQueueCommitter.queueAddition(AbstractFileQueueCommitter.java:143)
	at com.norconex.committer.core.AbstractCommitter.add(AbstractCommitter.java:96)
	at com.norconex.collector.core.pipeline.committer.CommitModuleStage.execute(CommitModuleStage.java:34)
	at com.norconex.collector.core.pipeline.committer.CommitModuleStage.execute(CommitModuleStage.java:27)
	at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:90)
	at com.norconex.collector.fs.crawler.FilesystemCrawler.executeCommitterPipeline(FilesystemCrawler.java:186)
	at com.norconex.collector.core.crawler.AbstractCrawler.processImportResponse(AbstractCrawler.java:534)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:491)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:377)
	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:735)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /opt/crawler/committer-queue/2016/05-01/01/48/43/1462110523645000000-add.cntnt (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:367)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:326)
	at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:1510)
	at com.norconex.committer.core.impl.FileSystemCommitter.add(FileSystemCommitter.java:98)
	... 13 more

**Comment by essiembre** [comment]
This is an frequent issue on Linux/Unix systems when the number of file handle that can be open at once is limited.  It seems this was exactly your case.

It is not something applications can control (other than trying to create less files).  Third party libraries used for parsing some file types or files with embedded objects can often produce tons of temporary files.  This is usually to avoid eating too much memory.   You can find several howtos online to solve this limit, like this one: https://easyengine.io/tutorials/linux/increase-open-files-limit/

I will keep this ticket open as a reminder to document that somewhere.

**Comment by essiembre** [comment]
I have added documentation for this problem to a new FAQ section on the Filesystem Collector website: http://www.norconex.com/collectors/collector-filesystem/faq
