### ISSUE TITLE
TIKA jar  errors

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-filesystem#9]
hi there 
after trying to work with your collector, that is very nice by the way,  i am getting some erros that i can point to TIKA jar according to this post 
[(https://issues.apache.org/jira/browse/TIKA-1947)]

my errors: 

> WARNING: Invalid format: "_([$$-240A]\ * \(#,##0.00\);"
java.lang.IllegalArgumentException: Unsupported [] format block '[' in '_([$$-240A]\ * \(#,##0.00\)' with c2: 

could you please point me out a way to fixed?
thanks

this is the full error trace:

> Sep 09, 2016 2:55:17 PM org.apache.poi.ss.format.CellFormat <init>
WARNING: Invalid format: "_([$$-240A]\ * \(#,##0.00\);"
java.lang.IllegalArgumentException: Unsupported [] format block '[' in '_([$$-240A]\ * \(#,##0.00\)' with c2: 
	at org.apache.poi.ss.format.CellFormatPart.formatType(CellFormatPart.java:365)
	at org.apache.poi.ss.format.CellFormatPart.getCellFormatType(CellFormatPart.java:279)
	at org.apache.poi.ss.format.CellFormatPart.<init>(CellFormatPart.java:183)
	at org.apache.poi.ss.format.CellFormat.<init>(CellFormat.java:167)
	at org.apache.poi.ss.format.CellFormat.getInstance(CellFormat.java:143)
	at org.apache.poi.ss.usermodel.DataFormatter.getFormat(DataFormatter.java:314)
	at org.apache.poi.ss.usermodel.DataFormatter.formatRawCellContents(DataFormatter.java:799)
	at org.apache.poi.ss.usermodel.DataFormatter.formatRawCellContents(DataFormatter.java:771)
	at org.apache.poi.xssf.eventusermodel.XSSFSheetXMLHandler.endElement(XSSFSheetXMLHandler.java:331)
	at org.apache.tika.parser.microsoft.ooxml.XSSFExcelExtractorDecorator$XSSFSheetInterestingPartsCapturer.endElement(XSSFExcelExtractorDecorator.java:359)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1776)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tika.parser.microsoft.ooxml.XSSFExcelExtractorDecorator.processSheet(XSSFExcelExtractorDecorator.java:195)
	at org.apache.tika.parser.microsoft.ooxml.XSSFExcelExtractorDecorator.buildXHTML(XSSFExcelExtractorDecorator.java:138)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:109)
	at org.apache.tika.parser.microsoft.ooxml.XSSFExcelExtractorDecorator.getXHTML(XSSFExcelExtractorDecorator.java:97)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:112)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
	at com.norconex.importer.parser.impl.AbstractTikaParser$MergeEmbeddedParser.parse(AbstractTikaParser.java:410)
	at com.norconex.importer.parser.impl.AbstractTikaParser.parseDocument(AbstractTikaParser.java:148)
	at com.norconex.importer.Importer.parseDocument(Importer.java:422)
	at com.norconex.importer.Importer.importDocument(Importer.java:318)
	at com.norconex.importer.Importer.doImportDocument(Importer.java:271)
	at com.norconex.importer.Importer.importDocument(Importer.java:195)
	at com.norconex.collector.core.pipeline.importer.ImportModuleStage.execute(ImportModuleStage.java:37)
	at com.norconex.collector.core.pipeline.importer.ImportModuleStage.execute(ImportModuleStage.java:26)
	at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91)
	at com.norconex.collector.fs.crawler.FilesystemCrawler.executeImporterPipeline(FilesystemCrawler.java:167)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:503)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:390)
	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:771)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at org.apache.poi.ss.format.CellFormatPart.<init>(CellFormatPart.java:183)
	at org.apache.poi.ss.format.CellFormat.<init>(CellFormat.java:167)
	at org.apache.poi.ss.format.CellFormat.getInstance(CellFormat.java:143)
	at org.apache.poi.ss.usermodel.DataFormatter.getFormat(DataFormatter.java:314)
	at org.apache.poi.ss.usermodel.DataFormatter.formatRawCellContents(DataFormatter.java:799)
	at org.apache.poi.ss.usermodel.DataFormatter.formatRawCellContents(DataFormatter.java:771)
	at org.apache.poi.xssf.eventusermodel.XSSFSheetXMLHandler.endElement(XSSFSheetXMLHandler.java:331)
	at org.apache.tika.parser.microsoft.ooxml.XSSFExcelExtractorDecorator$XSSFSheetInterestingPartsCapturer.endElement(XSSFExcelExtractorDecorator.java:359)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1776)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tika.parser.microsoft.ooxml.XSSFExcelExtractorDecorator.processSheet(XSSFExcelExtractorDecorator.java:195)
	at org.apache.tika.parser.microsoft.ooxml.XSSFExcelExtractorDecorator.buildXHTML(XSSFExcelExtractorDecorator.java:138)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:109)
	at org.apache.tika.parser.microsoft.ooxml.XSSFExcelExtractorDecorator.getXHTML(XSSFExcelExtractorDecorator.java:97)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:112)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
	at com.norconex.importer.parser.impl.AbstractTikaParser$MergeEmbeddedParser.parse(AbstractTikaParser.java:410)
	at com.norconex.importer.parser.impl.AbstractTikaParser.parseDocument(AbstractTikaParser.java:148)
	at com.norconex.importer.Importer.parseDocument(Importer.java:422)
	at com.norconex.importer.Importer.importDocument(Importer.java:318)
	at com.norconex.importer.Importer.doImportDocument(Importer.java:271)
	at com.norconex.importer.Importer.importDocument(Importer.java:195)
	at com.norconex.collector.core.pipeline.importer.ImportModuleStage.execute(ImportModuleStage.java:37)
	at com.norconex.collector.core.pipeline.importer.ImportModuleStage.execute(ImportModuleStage.java:26)
	at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91)
	at com.norconex.collector.fs.crawler.FilesystemCrawler.executeImporterPipeline(FilesystemCrawler.java:167)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:503)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:390)
	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:771)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by essiembre** [comment]
Without a copy of your config and document it is hard to tell.  Can you please attach both?

**Comment by angelo337** [comment]
hi there 
here as you see is my simple configuration, nothing fancy plain an simple.
would you please take a look for me?

thanks

[collector_fs.txt](https://github.com/Norconex/collector-filesystem/files/468413/collector_fs.txt)


[proceso.PDF.zip](https://github.com/Norconex/collector-filesystem/files/468409/proceso.PDF.zip)

**Comment by essiembre** [comment]
I cannot reproduce.  The file is getting parsed without issues when I try it with your config.   Which version of the collector are you using?  I tried with the latest.  You use the term "OCR" to name your crawler in your config, does that mean the error occurs when you enable OCR?  There is no OCR-related configuration in your file.

**Comment by angelo337** [comment]
Thanks for your answer, I see an issue is pretty much erratic, and I suppose is happening with  my configuration regarding Solr, but I am not sure why.
Regarding to the version my is: norconex-collector-filesystem-2.6.0

all OCR are process with an external software (Abbyy) in a batch jot, and I am tryning to index that files on my filesystem.

**Comment by essiembre** [comment]
Is the batch job changing the file before the collector picks it?  In any case, I tried enabling OCR within the Collector and in such case I do get an error triggered by parsing some of the images in your PDF (different error than yours).  I fixed that error and there is a new [snapshot release](https://www.norconex.com/collectors/collector-filesystem/download) with the fix in it.  I doubt it relates to your issue but you can try it just in case (make sure you install in a fresh dir to avoid Jar duplicates in the "lib" folder -- or check that carefully).

The collector also supports the open-source Tesseract OCR parser.  You may want to give it a try to see if you get different results.  You can configure that with the [GenericDocumentParserFactory](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/parser/GenericDocumentParserFactory.html).

**Comment by angelo337** [comment]
thanks a lot for your help, I will give a try, Iam having a different issue but with importer, I am going to open a case.
Regards
angelo
